# Generated by Django 5.2.9 on 2025-12-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='details',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='previous_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_rut',
            field=models.CharField(default='SISTEMA', max_length=12),
            preserve_default=False,
        ),
    ]
